### ISSUE TITLE
Поправить работу с типами данных

### ISSUE THREAD

**Issue by pingvin1308** [D-Rised/MeetApp#17]
https://github.com/D-Rised/MeetApp/blob/0bb148a19e453cb6ffedf9bb7d119b7dd4efb1d3/MeetApp.Web/Controllers/MeetController.cs#L50

Зачем делать парсинг в Guid самостоятельно, когда это уже заложено в стандартную десериализацию в asp.net core.
Ты можешь просто принимать Guid

**Comment by dariy-rised** [comment]
Исправил еще тогда)
