### ISSUE TITLE
Вывести интерфейс для сервисов и репозиториев

### ISSUE THREAD

**Issue by pingvin1308** [D-Rised/MeetApp#19]
https://github.com/D-Rised/MeetApp/blob/e1030a5b3737cee951833f61e7b0f745bf0117d9/MeetApp.Web/Startup.cs#L51

Предлагаю тебе познакомиться с такой концепцией как Dependency inversion или Invertion of control.
В рамках данного подхода тебе нужно будет вывести для сервисов и репозиториев интерфейсы.
После этого в коде заменить использование классов на соотвествующие интерфейсы.
И в DI зарегистрировать интерфейс и класс, которые его реализует.

Навсякий случай уточню, я говорю об этом :)
services.AddTransient<MeetRepository>();
services.AddTransient<UserService>();
services.AddTransient<MeetService>();

**Comment by dariy-rised** [comment]
Сделал)
