### ISSUE TITLE
Добавить метод для запроса встреч по userId

### ISSUE THREAD

**Issue by pingvin1308** [D-Rised/MeetApp#20]
Такая работа с данными конечно никуда не годится.  Что если этих встреч миллиарды?
https://github.com/D-Rised/MeetApp/blob/e1030a5b3737cee951833f61e7b0f745bf0117d9/MeetApp.Web/Services/MeetService.cs#L31

Вот нужно доработать этот метод :)
https://github.com/D-Rised/MeetApp/blob/e1030a5b3737cee951833f61e7b0f745bf0117d9/MeetApp.DAL/Repositories/MeetRepository.cs#L28

Ты ведь используешь ef core. Тут есть linq выражения, с помощью которых ты легко можешь вытащить данные.
Это точно нужно поправить

**Comment by D-Rised** [comment]
Сделано :)
