### ISSUE TITLE
Оптимизировать поиск встреч

### ISSUE THREAD

**Issue by pingvin1308** [D-Rised/MeetApp#5]
https://github.com/D-Rised/MeetApp/blob/9ea0d315590bbe613707207bbf7be1d101d8eee9/MeetApp.Web/Services/MeetService.cs#L76

В данном участке кода ты вытягиваешь все встречи из базы и затем обрабатываешь их на сервере. 
Пожалуй это не самый лучший подход, хотя он работает.

Как ты думаешь, почему такой подход не очень хорошо работает? :)
И как это можно поправить?

**Comment by D-Rised** [comment]
Я кажется понял, мы говорим о разных вещах. Я думал вы про вызов всех событий в главном меню, где нужны все все все события пользователя, а вы походу про SetupMeet, где нужно только конкретное событие, которое можно взять по  id, а я перебираю все события. Если это так, то извиняюсь за глупость, я это легко исправлю, добавив метод GetMeetById(Guid id), в этом нет проблем с пониманием.

**Comment by D-Rised** [comment]
Все во всех экшена, кроме MainMenu, оптимизировал алгоритм. Заодно исправил проблему с получением события по индексу списка, теперь все через GetMeetById, которые передается по ViewModel)
