### ISSUE TITLE
O_o - поправит названия аргументов

### ISSUE THREAD

**Issue by pingvin1308** [D-Rised/MeetApp#9]
https://github.com/D-Rised/MeetApp/blob/9ea0d315590bbe613707207bbf7be1d101d8eee9/MeetApp.Web/Controllers/MeetController.cs#L450

d1, d2 - это типо кубы чтоли? Типо как d6, d12? :)

было бы хотя бы date1 и date2, но это тоже фигово если честно.
Подумай как эти аргументы можно назвать получше

**Comment by D-Rised** [comment]
Исправил.
